version: '2'
services:
  web:
    container_name: LAMP
    build: .
    ports:
      - "80:80"
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
  db:
    image: mysql
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
